# Generated by Django 5.2.9 on 2026-01-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.PositiveBigIntegerField()),
                ('location', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
